### ISSUE TITLE
Adding Team Members

### ISSUE THREAD

**Issue by mnich0ls** [smartcityio/SanDiego2016#3]
Only smartcityio team members will see the SanDiego2016 channel/group on Gitter. Do you plan to add people to the team, or should we just update README.md to include the link to the channel/group? (https://gitter.im/smartcityio/SanDiego2016)

**Comment by merelyanode** [comment]
I'm adding everyone who submits an application to the team

**Comment by mnich0ls** [comment]
Ok, got it. Thanks!
